services:
  bot:
    image: awryme/reddit-exporter-bot
    volumes:
      - ./books:/app/books
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      BOT_TOKEN: ${BOT_TOKEN}
  server:
    image: awryme/reddit-exporter-server
    volumes:
      - ./books:/app/books
      - ./http_books:/app/http_books
    ports:
      - 8080:8080
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      BOT_TOKEN: ${BOT_TOKEN}
  samba:
    image: dockurr/samba
    environment:
      NAME: "RedditBooks"
      USER: "bookworm"
      PASS: ${SMB_PASS}
    ports:
      - 445:445
    volumes:
      - ./books:/storage
    restart: always
